### ISSUE TITLE
Adding an RSS feed is giving me issues

### ISSUE THREAD

**Issue by ItsNoted** [ssddanbrown/rss#14]
I cannot seem to get this RSS feed to work.
https://blog.networkprofile.org/rss

Any tips on why? Is it the sub domain? Can you replicate the issue?

Thanks
Jeremy

**Comment by ssddanbrown** [comment]
Seems to work from my test dev environment.
Added to my feeds exactly as:

```
https://blog.networkprofile.org/rss NotedTest2 #testing
```

Initially tried with a trailing slash on the URL, worked fine also.

I see the host is behind Cloudflare, which can often block requests. Could be that Cloudflare blocks your host IP or the requests to this host, thinking it's a bad bot to defends against. 
That would be my best guess, Have seen Cloudflare trip things up a few times while developing/testing this.

**Comment by ItsNoted** [comment]
For me it breaks the site giving it a 500 server error. https://snip.lol/KeRi8/RonuMayu65.png

Probably cloudflare but I'm adding several other blogs that are behind cloudflare including my own. Surprised you closed this so fast.

**Comment by ItsNoted** [comment]
Here's the exact list I am using.

https://noted.lol/rss Noted-⭐[#A800FF] #Self-Hosting
https://mediacowboy.tech/rss MediaCowboy #Self-Hosting

https://alexgallacher.com/rss/ Alex-Gallacher #Self-Hosting
https://oopsflavdidit.dev/rss/ Flavius #Self-Hosting
https://0x2142.com/rss Netowrking-Nonsense #Self-Hosting
https://dizzytech.de/index.xml DizzyTech #Self-Hosting
https://www.perrone.dev/rss/ Perrone.dev #Self-Hosting
https://breadnet.co.uk/rss/ breadNET #Self-Hosting
https://blog.kastanis.gr/rss/ sysadmin-daze #Self-Hosting
https://enchantedcode.co.uk/feed.xml Enchanted-Code #Self-Hosting
https://www.linuxserver.io/blog.rss LinuxServer Self-Hosting
https://www.smarthomebeginner.com/feed/ SmartHomeBeginner #Self-Hosting

https://itsfoss.com/rss/ itsFOSS #Open-Source
https://blog.opensource.org/feed OpenSourceOrg #Open-Source

https://feeds.fireside.fm/selfhosted/rss Self-Hosted-Show #Podcasts
https://thehomelab.show/feed TheHomelabShow #Podcasts

https://www.bleepingcomputer.com/feed/ Bleeping-Computer #Security

**Comment by ItsNoted** [comment]
My mistake. I saw the email for a closed case and it was for another one regarding env. I added the text file content above.

It works how it is there but if I add the new feed it breaks.

**Comment by ssddanbrown** [comment]
@ItsNoted Can you provide your exact feeds text file, in it's broken state?

**Comment by ItsNoted** [comment]
This is what is breaking it. You can see the feed I am trying to add that breaks it on line 3.

```
https://noted.lol/rss Noted-⭐[#A800FF] #Self-Hosting
https://mediacowboy.tech/rss MediaCowboy #Self-Hosting
https://blog.networkprofile.org/rss NetworkingProfile #Self-Hosting
https://alexgallacher.com/rss/ Alex-Gallacher #Self-Hosting
https://oopsflavdidit.dev/rss/ Flavius #Self-Hosting
https://0x2142.com/rss Netowrking-Nonsense #Self-Hosting
https://dizzytech.de/index.xml DizzyTech #Self-Hosting
https://www.perrone.dev/rss/ Perrone.dev #Self-Hosting
https://breadnet.co.uk/rss/ breadNET #Self-Hosting
https://blog.kastanis.gr/rss/ sysadmin-daze #Self-Hosting
https://enchantedcode.co.uk/feed.xml Enchanted-Code #Self-Hosting
https://www.linuxserver.io/blog.rss LinuxServer Self-Hosting
https://www.smarthomebeginner.com/feed/ SmartHomeBeginner #Self-Hosting

https://itsfoss.com/rss/ itsFOSS #Open-Source
https://blog.opensource.org/feed OpenSourceOrg #Open-Source

https://feeds.fireside.fm/selfhosted/rss Self-Hosted-Show #Podcasts
https://thehomelab.show/feed TheHomelabShow #Podcasts

https://www.bleepingcomputer.com/feed/ Bleeping-Computer #Security
```

**Comment by ssddanbrown** [comment]
I can't get that to break on my dev instance (Which is effectively running the version as published today).

Within your mounted `/app/storage` volume you should have a `logs/laravel.log` which may have more information. Tail the last 100 lines of that and look for an error appearing at the time time as you see the error in your screenshot.

**Comment by ItsNoted** [comment]
Seems odd that it would be a permission issue but this is the error I see.

```
production.ERROR: Unable to create lockable file: /app/storage/framework/cache/data/58/0b/580b3006ff98135e85afeb244fcfa12a74bd3384. Please ensure you have permission to create files in this location. {"exception":"[object] (Exception(code: 0): Unable to create lockable file: /app/storage/framework/cache/data/58/0b/580b3006ff98135e85afeb244fcfa12a74bd3384. Please ensure you have permission to create files in this location. at /app/vendor/laravel/framework/src/Illuminate/Filesystem/LockableFile.php:73)
```

**Comment by ItsNoted** [comment]
Here are some logs from today.

https://snip.lol/KeRi8/hEdoDatE95.txt/raw

**Comment by ssddanbrown** [comment]
Might be worth trying a `sudo chmod -R 777 <container_volume_mount_folder>` just to make those folders/files read+writable for all to see if that alleviates the current issue.

**Comment by ItsNoted** [comment]
> Might be worth trying a `sudo chmod -R 777 <container_volume_mount_folder>` just to make those folders/files read+writable for all to see if that alleviates the current issue.

Bingo. That did it. Wonder why though as all the others added just fine seemingly.

**Comment by ssddanbrown** [comment]
Wooo! :partying_face: 
Probably nothing to do with that specific feed, but just that the addition of a new feed would trigger a queue process, which needed to create a lock via cache, which would conflict via permissions.

Not sure why permission may differ though, depends on how the files/folders have been handled. 
Not sure either on best practices either for these scenarios, and whether the container application should be blasting its own permissions or not.

**Comment by ItsNoted** [comment]
I appreciate your full attention on this matter and quick response. I know you're really busy and I very much appreciate it!
