### ISSUE TITLE
failed to parse some rss

### ISSUE THREAD

**Issue by livid123** [ssddanbrown/rss#15]
parseRssDataToPosts -> isValidPostData failed on "https://www.gqdm.net/index.php/rss/index.xml"

**Comment by ssddanbrown** [comment]
Hi @livid123,
It looks like the format of the dates within the feed is tripping things up, since they're non-standard for RSS.
Can validate this here: https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.gqdm.net%2Findex.php%2Frss%2Findex.xml
