### ISSUE TITLE
[Future Request] Keyword Filtering in RSS Feeds

### ISSUE THREAD

**Issue by dhanadhan** [ssddanbrown/rss#23]
It would be awesome to have a keyword filtering to either not show or only show matching rss feeds. Multiple keyword support if possible. Similar to what this app does: [Examples](https://docs.monitorss.xyz/bot-customizations/filters/filters-regular#examples)

If a matching keyword(s) is found in a title or description, it will only show those posts
If a matching keyword(s) is found with negation in titles or description, it will not show those posts. 

Example,
Title1: This is just a title
Title2: This is a title

Config: https://link.com SomeFeedName ~just
- Symbol "~" could represent negate feeds which means any title/description found to have "just" will not show, deleted in other word. Title 1 will not show with this example. 

Config: https://link.com SomeFeedName +just
- Symbol "+" could represent show feeds which means any title/description found to have "just" will show. Only Title1 will show with this example, every other titles will not show or deleted.

I would really appreciate this feature if it gets added. It would help to filter out a lot of unnecessary posts and only view sort listed posts we are interested in. 

Thanks

**Comment by ssddanbrown** [comment]
Thanks for offering the suggestion @dhanadhan, but as per the [project readme](https://github.com/ssddanbrown/rss#low-maintenance-project) I aim to keep the scope of this project fixed/limited to reduce maintenance effort, so I'm not looking to add features or take on feature requests in this repo. Therefore I'm going to close this off.

If you'd like to attempt this on your own custom fork, and would like high-level general guidance in making changes, feel free to still comment on this thread.
