### ISSUE TITLE
no thumbnails from reddit rss

### ISSUE THREAD

**Issue by Famku** [ssddanbrown/rss#25]
Hi,

it seems that there no thumbnails generated from reddit rss.

I raised a issue in the past with the same problem and you solved it.

Can you please check again?

**Comment by ssddanbrown** [comment]
This app looks for the opengraph image in the source of the URL for the RSS item.
Looking at reddit pages, I can't seem to see those in the source, although some other tools pick them up and I'm sometimes seeing them in the DOM.

Might be that Reddit no longer (simply) supports the standard of thumbnail image we're using, or has broken thier functionality or is making changes.

**Comment by Famku** [comment]
ok, thanks for the quick answer
