### ISSUE TITLE
How can I toggle the dark mode to light?

### ISSUE THREAD

**Issue by christoney** [ssddanbrown/rss#27]
Now that it is warming up in this area, I am outside more and dark mode is less relevant. How can I change from dark mode to light mode?

Thanks from Wisconsin USA

**Comment by ssddanbrown** [comment]
Hi @christoney,
The mode is driven by browser/OS light/dark mode preference. There is no setting within the app itself.

**Comment by christoney** [comment]
Thanks Dan!
