### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by mariushosting** [ssddanbrown/rss#28]
I suggest to add Dark Mode as a theme switch!

**Comment by ssddanbrown** [comment]
Thanks for the suggestion @mariushosting, but this isn't a feature I desire/need at all, and as per the ["Low Maintenance Project" part of the readme](https://github.com/ssddanbrown/rss?tab=readme-ov-file#low-maintenance-project) I don't want to widen the scope where not needed. So I'll therefore close this off.
