### ISSUE TITLE
 cURL error 6 when fetching feed

### ISSUE THREAD

**Issue by airdogvan** [ssddanbrown/rss#3]
I can get the web page, but it keeps saying "reloading feeds".

Logs:
rss    | [2022-07-04 19:04:56][28] Processing: App\Jobs\RefreshFeedJob
rss    | [2022-07-04 19:04:56][29] Processing: App\Jobs\RefreshFeedJob
rss    | [2022-07-04 19:04:56][30] Processing: App\Jobs\RefreshFeedJob
rss    | [2022-07-04 19:04:56][30] Failed:     App\Jobs\RefreshFeedJob
rss    | [2022-07-04 19:05:02][31] Processing: App\Jobs\RefreshFeedJob
rss    | [2022-07-04 19:05:02][32] Processing: App\Jobs\RefreshFeedJob
rss    | [2022-07-04 19:05:02][33] Processing: App\Jobs\RefreshFeedJob
rss    | [2022-07-04 19:05:02][33] Failed:     App\Jobs\RefreshFeedJob

Tried with both:

https://feeds.theguardian.com/theguardian/world/rss Guardian_World
and 
https://news.ycombinator.com/rss Hacker_news

I know these 2 feeds are valid as I use them in Freshrss.

Also tried with:
https://rss.nytimes.com/services/xml/rss/nyt/World.xml NY_Times

to be sure the problem wasn't with the xml extension...

**Comment by ssddanbrown** [comment]
Hi @airdogvan,
Just tested things with all 3 of those feeds, copying and pasting the text provided above into my `feeds.txt`, and all could import without issue. Only minor issue I saw was trouble fetching ntyimes article images, but all feeds themselves worked okay.

Does your container definitely have outbound internet access? 
Otherwise, you may have more detail in the `logs/laravel.log` file within the mounted `/app/storage` volume.

**Comment by Famku** [comment]
I have the same error message on all feeds.

for example the feed from yor screenshot:

[previous exception] [object] (GuzzleHttp\\Exception\\ConnectException(code: 0): cURL error 6: getaddrinfo() thread failed to start (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://www.omgubuntu.co.uk/feed.xml at /app/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:210)
[stacktrace]

**Comment by ssddanbrown** [comment]
@Famku Could you confirm hosting operating system and system architecture (AMD64, ARM64) in use?

**Comment by airdogvan** [comment]
ok can't get the beginning because the container does not provide "less" but I can paste a few lines of the laravel log:

#35 /app/vendor/symfony/console/Application.php(171): Symfony\\Component\\Console\\Application->doRun()
#36 /app/vendor/laravel/framework/src/Illuminate/Console/Application.php(102): Symfony\\Component\\Console\\Application->run()
#37 /app/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#38 /app/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#39 {main}

[previous exception] [object] (GuzzleHttp\\Exception\\ConnectException(code: 0): cURL error 6: getaddrinfo() thread failed to start (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://news.ycombinator.com/rss at /app/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:210)
[stacktrace]
#0 /app/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(158): GuzzleHttp\\Handler\\CurlFactory::createRejection()
#1 /app/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(110): GuzzleHttp\\Handler\\CurlFactory::finishError()
#2 /app/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(47): GuzzleHttp\\Handler\\CurlFactory::finish()
#3 /app/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\\Handler\\CurlHandler->__invoke()
#4 /app/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(48): GuzzleHttp\\Handler\\Proxy::GuzzleHttp\\Handler\\{closure}()
#5 /app/vendor/laravel/framework/src/Illuminate/Http/Client/PendingRequest.php(1095): GuzzleHttp\\Handler\\Proxy::GuzzleHttp\\Handler\\{closure}()
#6 /app/vendor/laravel/framework/src/Illuminate/Http/Client/PendingRequest.php(1061): Illuminate\\Http\\Client\\PendingRequest->Illuminate\\Http\\Client\\{closure}()
#7 /app/vendor/laravel/framework/src/Illuminate/Http/Client/PendingRequest.php(1047): Illuminate\\Http\\Client\\PendingRequest->Illuminate\\Http\\Client\\{closure}()
#8 /app/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(35): Illuminate\\Http\\Client\\PendingRequest->Illuminate\\Http\\Client\\{closure}()
#9 /app/vendor/guzzlehttp/guzzle/src/Middleware.php(37): GuzzleHttp\\PrepareBodyMiddleware->__invoke()
#10 /app/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(71): GuzzleHttp\\Middleware::GuzzleHttp\\{closure}()
#11 /app/vendor/guzzlehttp/guzzle/src/Middleware.php(61): GuzzleHttp\\RedirectMiddleware->__invoke()
#12 /app/vendor/guzzlehttp/guzzle/src/HandlerStack.php(75): GuzzleHttp\\Middleware::GuzzleHttp\\{closure}()
#13 /app/vendor/guzzlehttp/guzzle/src/Client.php(331): GuzzleHttp\\HandlerStack->__invoke()
#14 /app/vendor/guzzlehttp/guzzle/src/Client.php(168): GuzzleHttp\\Client->transfer()
#15 /app/vendor/guzzlehttp/guzzle/src/Client.php(187): GuzzleHttp\\Client->requestAsync()
#16 /app/vendor/laravel/framework/src/Illuminate/Http/Client/PendingRequest.php(905): GuzzleHttp\\Client->request()
#17 /app/vendor/laravel/framework/src/Illuminate/Http/Client/PendingRequest.php(779): Illuminate\\Http\\Client\\PendingRequest->sendRequest()
#18 /app/vendor/laravel/framework/src/Illuminate/Support/helpers.php(243): Illuminate\\Http\\Client\\PendingRequest->Illuminate\\Http\\Client\\{closure}()
#19 /app/vendor/laravel/framework/src/Illuminate/Http/Client/PendingRequest.php(817): retry()
#20 /app/vendor/laravel/framework/src/Illuminate/Http/Client/PendingRequest.php(658): Illuminate\\Http\\Client\\PendingRequest->send()
#21 /app/app/Rss/FeedPostFetcher.php(21): Illuminate\\Http\\Client\\PendingRequest->get()

**Comment by Famku** [comment]
its AMD64

**Comment by ssddanbrown** [comment]
Thanks @airdogvan, So same issue as @Famku,

Are you able to confirm hosting operating system and system architecture (AMD64, ARM64) in use?

**Comment by ssddanbrown** [comment]
@Famku What operating system is the host running on?

**Comment by Famku** [comment]
Ubuntu 20.04.4 LTS

**Comment by airdogvan** [comment]
AMD 64 with Ubuntu 20.04 LTS

**Comment by airdogvan** [comment]
Ok, was able to install "less" in container, so this is the beginning of the log file.  Please note that it's trying to read the "Guardian" feed although that line begins with a #, so should be not be processed according to your doc...

[2022-07-04 18:47:45] production.ERROR: cURL error 6: getaddrinfo() thread failed to start (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://feeds.theguardian.com/theguardian/world/rss {"except
ion":"[object] (Illuminate\\Http\\Client\\ConnectionException(code: 0): cURL error 6: getaddrinfo() thread failed to start (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://feeds.theguardian.co
m/theguardian/world/rss at /app/vendor/laravel/framework/src/Illuminate/Http/Client/PendingRequest.php:809)
[stacktrace]
#0 /app/vendor/laravel/framework/src/Illuminate/Support/helpers.php(243): Illuminate\\Http\\Client\\PendingRequest->Illuminate\\Http\\Client\\{closure}()
#1 /app/vendor/laravel/framework/src/Illuminate/Http/Client/PendingRequest.php(817): retry()
#2 /app/vendor/laravel/framework/src/Illuminate/Http/Client/PendingRequest.php(658): Illuminate\\Http\\Client\\PendingRequest->send()
#3 /app/app/Rss/FeedPostFetcher.php(21): Illuminate\\Http\\Client\\PendingRequest->get()
#4 /app/app/Jobs/RefreshFeedJob.php(39): App\\Rss\\FeedPostFetcher->fetchForFeed()

**Comment by ssddanbrown** [comment]
Thanks both,
This is a strange one then. I run & test it using the AMD64 image on both Fedora 36 and Ubuntu 22.04.
I'm just setting up an environment to test in Ubuntu 20.04.

**Comment by airdogvan** [comment]
thanks for your trouble.... nice to see a dev standing behind his work :)

**Comment by ssddanbrown** [comment]
Okay, I tested this on a Ubuntu 20.04 instance and it still worked. Might have altered results though since I was running Ubuntu on an LXC container on another host.

While searching, I did come [across this](https://askubuntu.com/questions/1405417/20-04-vs-22-04-inside-docker-with-a-16-04-host-thread-start-failures) which may be relevant. Seems to be some issues with running newer images on older Ubuntu versions due to security feature library issues.

It might be worth running this container with the `--security-opt seccomp=unconfined`  option (If using CLI) or via adding a `security_opt` part to our docker-compose like so:

```yml
---
version: "2"
services:
    rss:
        image: ghcr.io/ssddanbrown/rss:latest
        container_name: rss
        security_opt:
          - seccomp:unconfined
        environment:
            - APP_NAME=RSS
        volumes:
            - ./rss-files:/app/storage
        ports:
            - "8080:80"
        restart: unless-stopped
```

**Comment by airdogvan** [comment]
OK, that worked for me, thanks so much...!!!

**Comment by ssddanbrown** [comment]
@airdogvan Ah, Thanks for confirming!

Not really sure on the proper remedy though, downgrading the docker base image to work around a host-specific bug seems awkward. Maybe I'll just add a note to the project readme, with the info above, if I get any more reports.

**Comment by Famku** [comment]
I installed it on another Ubuntu 22.04 LTS host -- works

thank you

**Comment by minyk** [comment]
CentOS 7.9 also works fine

**Comment by ssddanbrown** [comment]
Cool, Thanks all for confirming.
I'll therefore go ahead and close this off but I'll keep watch and add some guidance to the readme if this becomes a common pain-point.
