### ISSUE TITLE
Retention of data

### ISSUE THREAD

**Issue by aobh** [ssddanbrown/rss#7]
Hi @ssddanbrown 

Thanks for the great tool! Been using it for a couple of days now and love it!

One question though. Is there any retention of the data in place? I added quite some feeds and I am at 622MB for the App/public/thumbs and about 4,6MB for the database.

Thanks!

Greetings,
Michiel

**Comment by ssddanbrown** [comment]
Hi @aobh,

As long as you've mounted a volume to the `/app/storage` container directory, as shown in our example composer or CLI commands, then you should have image and database data retained on the host system.

**Comment by aobh** [comment]
Hi @ssddanbrown ,

Sorry, I used the wrong wording I think. I was more thinking about trimming. I am using a separate volume for it, and storage is not an issue at the moment. But I know myself and I wont look at this for a while and then all of sudden its huge ;-).

Greetings,
Michiel

**Comment by ssddanbrown** [comment]
I've added functionality for pruning old post data within PR #8.
This has been released under v1.1.0, info can be seen in release details: https://github.com/ssddanbrown/rss/releases/tag/v1.1.0
Does this added functionality appease your concerns?

**Comment by aobh** [comment]
Hi @ssddanbrown !

Thanks for the functionality! I am also a big fan of Bookstack! 

I downloaded the new docker image and changed the ENV settings and restarted. Changed it to 7 days. However the size is still the same on storage. When does the pruning run? It mentions once a day. Is that on a specific time?

Thanks again!

**Comment by ssddanbrown** [comment]
> When does the pruning run? It mentions once a day. Is that on a specific time?

I think it might run at exactly midnight (Not sure if UTC or system-local-timezone).
Let me know if there's no change after a day.

**Comment by aobh** [comment]
Hi @ssddanbrown ,

Its working like a charm! The data was pruned from 1,4 gig to 560MB!

**Comment by ssddanbrown** [comment]
Woo :partying_face: 

I'll therefore close this off.
