### ISSUE TITLE
Use of own RSS apps

### ISSUE THREAD

**Issue by lubbertkramer** [ssddanbrown/rss#9]
Love your work what you did here (and with Bookstack) but I have a question/feature request: 

Does your RSS app has an API or Fever so that it can be used with any mobile app that supports Fever/API like Fiery Feeds or other RSS reader or are you planning this as a future feature?

**Comment by ssddanbrown** [comment]
> Love your work what you did here (and with Bookstack)

Thanks!

> Does your RSS app has an API or Fever so that it can be used with any mobile app that supports Fever/API like Fiery Feeds or other RSS reader or are you planning this as a future feature?

No, No external API or client support is planned. The scope is a simple web RSS feed reader, and I don't want to expand the scope here for use/compability with other readers or reader technologies, or to maintain an extra API.
